# Generated by Django 6.0.4 on 2026-04-25 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='playto_user',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pt_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='playto_account_directory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number_encrypted', models.TextField()),
                ('account_number_hash', models.CharField(db_index=True, max_length=255)),
                ('bank_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('puid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.playto_user')),
            ],
        ),
        migrations.CreateModel(
            name='playto_payout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('retry_count', models.IntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playto_account_directory')),
                ('puid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.playto_user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('puid', 'idempotency_key'), name='unique_puid_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='playto_ledger_entries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], max_length=20)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.playto_user')),
            ],
            options={
                'indexes': [models.Index(fields=['puid', 'created_at'], name='core_playto_puid_id_cec2df_idx')],
            },
        ),
    ]
